/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mnnit.server.ui;

import javax.swing.JFrame;

/**
 *
 * @author Lakhan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainChatArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connectMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        clearChatMenuItem = new javax.swing.JMenuItem();
        setAwayChatItem = new javax.swing.JMenuItem();
        settingsChatItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutChatItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ServerLEssChat");

        mainChatArea.setColumns(20);
        mainChatArea.setRows(5);
        jScrollPane1.setViewportView(mainChatArea);

        jScrollPane2.setViewportView(userList);

        jTextField1.setMaximumSize(new java.awt.Dimension(6, 2147483647));

        fileMenu.setText("File");

        connectMenuItem.setText("Reconnect");
        fileMenu.add(connectMenuItem);

        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        jMenuBar1.add(fileMenu);

        toolsMenu.setText("Tools");

        clearChatMenuItem.setText("Clear Chat");
        toolsMenu.add(clearChatMenuItem);

        setAwayChatItem.setText("Set Away");
        toolsMenu.add(setAwayChatItem);

        settingsChatItem.setText("Settings");
        settingsChatItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsChatItemActionPerformed(evt);
            }
        });
        toolsMenu.add(settingsChatItem);

        jMenuBar1.add(toolsMenu);

        helpMenu.setText("Help");

        aboutChatItem.setText("About");
        aboutChatItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutChatItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutChatItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutChatItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutChatItemActionPerformed
        Thread th = new Thread(){
                public void run()
                {
                      JFrame aboutFrame = new AboutFrame();
                      if(aboutFrame!=null){
                        aboutFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        aboutFrame.setVisible(true);
                      }
                      else
                      {
                          System.out.println("About frame is null. Do something about it");
                      }
                }
            };
        th.start();
    }//GEN-LAST:event_aboutChatItemActionPerformed

    private void settingsChatItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsChatItemActionPerformed
        
        Thread th = new Thread(){
                public void run()
                {
                      JFrame settingsFrame = new SettingsFrame();
                      settingsFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                      settingsFrame.setVisible(true);
                }
            };
        th.start();
    }//GEN-LAST:event_settingsChatItemActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutChatItem;
    private javax.swing.JMenuItem clearChatMenuItem;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea mainChatArea;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem setAwayChatItem;
    private javax.swing.JMenuItem settingsChatItem;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JList userList;
    // End of variables declaration//GEN-END:variables
}
